services:
  datahost:
    networks:
      - default
      - webproxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=webproxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-datahost.rule=Host(`gateway.sc2arcade.com`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-datahost.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-datahost.tls.certresolver=le-http"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME:??}-datahost.loadbalancer.server.port=8089"
  
  webapi:
    networks:
      - default
      - webproxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=webproxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-webapi.rule=Host(`api.sc2arcade.com`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-webapi.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-webapi.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-webapi.middlewares=real-ip-cf@file"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-static.rule=Host(`static.sc2arcade.com`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-static.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-static.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-static.middlewares=real-ip-cf@file"

networks:
  webproxy:
    name: webproxy
    external: true
