services:
  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: ${COMPOSE_PROJECT_NAME:??}-prom-mysqld-exporter
    command:
      - "--collect.global_status"
      - "--collect.global_variables"
      - "--collect.engine_innodb_status"
    environment:
      DATA_SOURCE_NAME: exporter:exporter@(mariadb:3306)/
    external_links:
      - "${COMPOSE_PROJECT_NAME:??}-mariadb:mariadb"
    expose:
      - 9104

  node-exporter:
    image: prom/node-exporter:latest
    container_name: ${COMPOSE_PROJECT_NAME:??}-prom-node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - source: /mnt/data/prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        type: bind
        read_only: true
        bind:
          create_host_path: false
      - type: volume
        source: prometheus_data
        target: /prometheus
        volume:
          nocopy: true
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    external_links:
      - "${COMPOSE_PROJECT_NAME:??}-prom-node-exporter:node-exporter"
      - "${COMPOSE_PROJECT_NAME:??}-prom-mysqld-exporter:mysqld-exporter"
    expose:
      - 9090

volumes:
  prometheus_data:
