x-service-volumes: &service_volumes
  volumes:
    - source: ./
      target: /app
      type: bind

x-service-build: &service_build
  context: .
  target: app-dev


services:
  redis:
    networks:
      - default
      - dbproxy

  mariadb:
    networks:
      - default
      - dbproxy

  datahost:
    <<: [ *service_volumes ]
    build:
      <<: [ *service_build ]

  dataproc:
    <<: [ *service_volumes ]
    build:
      <<: [ *service_build ]

  webapi:
    <<: [ *service_volumes ]
    build:
      <<: [ *service_build ]
    networks:
      - default
      - webproxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=webproxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-webapi.rule=Host(`api-sc2arcade.site.localhost`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-webapi.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-webapi.tls=true"

  drec:
    <<: [ *service_volumes ]
    build:
      <<: [ *service_build ]

  dsbot:
    <<: [ *service_volumes ]
    build:
      <<: [ *service_build ]

  btrack:
    <<: [ *service_volumes ]
    build:
      <<: [ *service_build ]

  cron:
    <<: [ *service_volumes ]
    build:
      <<: [ *service_build ]

networks:
  webproxy:
    name: webproxy
    external: true

  dbproxy:
    name: dbproxy
    external: true
