services:
  redis:
    networks:
      - default
      - dbproxy
    healthcheck:
      test: 'redis-cli ping || exit 1'
      start_period: 5s
      interval: 10s
      timeout: 10s
      retries: 10

  mariadb:
    networks:
      - default
      - dbproxy
    healthcheck:
      test: 'mysqladmin ping --user=${STARC_SQL_USER-db} --password=${STARC_SQL_PASSWORD-db}'
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 30

  datahost:
    networks:
      - default
      - webproxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=webproxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-datahost.rule=Host(`gateway.sc2arcade.com`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-datahost.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-datahost.tls.certresolver=le-http"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME:??}-datahost.loadbalancer.server.port=8089"
    stop_grace_period: 20s
    depends_on:
      redis: { condition: service_healthy }
      mariadb: { condition: service_healthy }

  dataproc:
    stop_grace_period: 20s
    depends_on:
      redis: { condition: service_healthy }
      mariadb: { condition: service_healthy }

  webapi:
    networks:
      - default
      - webproxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=webproxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-webapi.rule=Host(`api.sc2arcade.com`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-webapi.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-webapi.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-webapi.middlewares=real-ip-cf@file"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-static.rule=Host(`static.sc2arcade.com`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-static.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-static.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-static.middlewares=real-ip-cf@file"
    stop_grace_period: 30s
    depends_on:
      redis: { condition: service_healthy }
      mariadb: { condition: service_healthy }

  drec:
    stop_grace_period: 45s
    depends_on:
      redis: { condition: service_healthy }
      mariadb: { condition: service_healthy }

  dsbot:
    stop_grace_period: 45s
    depends_on:
      redis: { condition: service_healthy }
      mariadb: { condition: service_healthy }

  btrack:
    stop_grace_period: 30s
    depends_on:
      redis: { condition: service_healthy }
      mariadb: { condition: service_healthy }

networks:
  webproxy:
    name: webproxy
    external: true

  dbproxy:
    name: dbproxy
    external: true
